### ISSUE TITLE
upload_and_update.py: Errors on updating BMC

### ISSUE THREAD

**Issue by mine260309** [openbmc/openbmc-tools#13]
With recent OpenBMC builds, this script sometimes fails to update BMC with below error:
```
Preserve network...
{
  "data": {
    "description": "The specified resource cannot be created: '/org/openbmc/control/flash/bmc'"
  },
  "message": "403 Forbidden",
  "status": "error"
}Update via TFTP...
{
  "data": {
    "description": "org.freedesktop.DBus.Error.FileNotFound: path or object not found: /org/openbmc/control/flash/bmc"
  },
  "message": "404 Not Found",
  "status": "error"
}Waiting for downloading...
```

This is caused by the legacy obmc flash service lowered its priority, and is not started when the script tries to use it.

**Comment by geissonator** [comment]
Yeah, that wasn't very nice of me to lower those (https://gerrit.openbmc-project.xyz/#/c/8627/).  We've removed them entirely from witherspoon now to address the reboot performance issues so we should just bump them back up since they are not legacy services on systems that use them.
