### ISSUE TITLE
No "xyz.openbmc_project.State.Host.Error.SoftOffTimeout" in policy table

### ISSUE THREAD

**Issue by xuweibj** [openbmc/openbmc-tools#26]
I got eventlog ``xyz.openbmc_project.State.Host.Error.SoftOffTimeout``, but could not find this in policy table.

**Comment by amboar** [comment]
@thalerj can you take a look at this?

**Comment by thalerj** [comment]
@amboar Working on an update now.

**Comment by amboar** [comment]
Can we close this @thalerj ?

**Comment by thalerj** [comment]
Yes please do.
