### ISSUE TITLE
openbmctool:  health check failed

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-tools#35]
openbmctool version = 1.06

On one of our systems, saw this:
bash-4.1$ python3 openbmctool.py -H $BMC -U xxxxxx -P xxxxxx health_check

Attempting login...
Traceback (most recent call last):
 File "openbmctool.py", line 2125, in <module>
   main()
 File "openbmctool.py", line 2099, in main
   output = args.func(args.host, args, mysess)
 File "openbmctool.py", line 1548, in healthCheck
   sels = json.loads(selPrint(host, args, session))
 File "/opt/rh/rh-python34/root/usr/lib64/python3.4/json/__init__.py", line 312, in loads
   s.__class__.__name__))
TypeError: the JSON object must be str, not 'dict'

**Comment by thalerj** [comment]
This may be due to a network timeout or similar error during the requests.

**Comment by amboar** [comment]
> This may be due to a network timeout or similar error during the requests.

I don't think that's properly substantiated. The type that was received was wrong; it's not immediately obvious to me that can be a fault of the network.

**Comment by ssombar** [comment]
Cancelling.   Will reopen if an issue again.
