### ISSUE TITLE
openbmctool:    two versions 

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-tools#39]
Version 1.07 of the openbmctool has logging functions.    Version 1.09 is more robust but does not support logging.   Can we perhaps have a new version which is a merge of both?

Version 1.09 is available from here
 https://www14.software.ibm.com/support/customercare/sas/f/lopdiags/scaleOutLCdebugtool.html

Version 1.07 is available from here:
 git clone  https://github.com/openbmc/openbmc-tools/    then look for thalerj

**Comment by thalerj** [comment]
version 1.10 is posted for a merge here and contains all the content from both levels. : https://github.com/openbmc/openbmc-tools/pull/46
