### ISSUE TITLE
steps to run rootfs_size.py

### ISSUE THREAD

**Issue by priyanka611** [openbmc/openbmc-tools#49]
I want to reduce size of openbmc rootfs file to run on ast2500 board, I got one suggestion to use rootfs_size.py script .I  dont know where to run this script and which command to run the script. Can anyone provide steps to run this script.

Thanks in advance

**Comment by geissonator** [comment]
https://github.com/openbmc/openbmc-tools/blob/master/edtanous/rootfs_size.py should be pretty self explanatory. You bitbake your image then pass in those 2 parameters which are your base build directory and the path to your squashfs. It'll take a few hours to complete.
