### ISSUE TITLE
[enhancement request] openbmctool.py reader friendly sorting of FRU list

### ISSUE THREAD

**Issue by kyle-ibm** [openbmc/openbmc-tools#6]
@thalerj Is it possible to have the fru status sort to be more reader friendly?
i.e. instead of 0,1,10,11... list out 0,1,2,3,4.....
./openbmctool.py -H wsp001 -U root -P 0penBmc fru status
..
cpu1         | Yes       | Yes      | Yes         | Yes       
cpu1-core0   | No        | No       | No          | No        
cpu1-core1   | No        | Yes      | Yes         | No        
cpu1-core10  | No        | Yes      | Yes         | No        
cpu1-core11  | No        | Yes      | Yes         | No        
cpu1-core12  | No        | No       | No          | No        
cpu1-core13  | No        | No       | No          | No        
cpu1-core14  | No        | Yes      | Yes         | No        
cpu1-core15  | No        | Yes      | Yes         | No        
cpu1-core16  | No        | No       | No          | No        
cpu1-core17  | No        | No       | No          | No        
cpu1-core18  | No        | Yes      | Yes         | No        
cpu1-core19  | No        | Yes      | Yes         | No        
cpu1-core2   | No        | Yes      | Yes         | No        
cpu1-core20  | No        | Yes      | Yes         | No        
cpu1-core21  | No        | No       | No          | No        
cpu1-core22  | No        | Yes      | Yes         | No        
cpu1-core23  | No        | Yes      | Yes         | No        
cpu1-core3   | No        | Yes      | Yes         | No        
cpu1-core4   | No        | No       | No          | No        
cpu1-core5   | No        | No       | No          | No        
cpu1-core6   | No        | Yes      | Yes         | No        
cpu1-core7   | No        | Yes      | Yes         | No        
cpu1-core8   | No        | Yes      | No          | No        
cpu1-core9   | No        | Yes      | No          | No        
dimm0        | Yes       | Yes      | Yes         | No        
dimm1        | Yes       | Yes      | Yes         | No        
dimm10       | Yes       | Yes      | Yes         | No        
dimm11       | Yes       | Yes      | Yes         | No        
dimm12       | Yes       | Yes      | Yes         | No        
dimm13       | Yes       | Yes      | Yes         | No        
dimm14       | Yes       | Yes      | Yes         | No        
dimm15       | Yes       | Yes      | Yes         | No        
dimm2        | Yes       | Yes      | Yes         | No        
dimm3        | Yes       | Yes      | Yes         | No        
dimm4        | Yes       | Yes      | Yes         | No        
dimm5        | Yes       | Yes      | Yes         | No        
dimm6        | Yes       | Yes      | Yes         | No        
dimm7        | Yes       | Yes      | Yes         | No        
dimm8        | Yes       | Yes      | Yes         | No        
dimm9        | Yes       | Yes      | Yes         | No

**Comment by amboar** [comment]
I can't assign @thalerj at the moment. @geissonator @bradbishop can we get him added to one of the organisation's groups?

**Comment by thalerj** [comment]
This has been addressed. Please close.
